settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '并非所有系统运行正常'
  monitorLabelOperational: '运行正常'
  monitorLabelNotOperational: '运行异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog-hpcesia-com # unique identifier
    name: blog.hpcesia.com
    description: '个人博客' # default=empty
    url: 'https://blog.hpcesia.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: statistic-hpcesia-com
    name: statistic.hpcesia.com
    description: '站点访问统计'
    url: 'https://statistic.hpcesia.com/'
    method: GET
    expectStatus: 200
    linkable: true
